use flywell_db;
delete from flight_reservation_form_map;
delete from flight_reservation_seat_map;
delete from flight_instance_reservations;
delete from flight_reservation;
delete from flight_instance_seats;
delete from flight_instance;
delete from flight;
delete from user_otps;
delete from user_roles;
delete from otp;
delete from user;
delete from airport;
