use flywell_db;
delete from flight_reservation_form_map;
delete from flight_reservation_seat_map;
delete from flight_instance_reservations;
delete from flight_reservation;
delete from flight_instance_seats;
delete from flight_instance;
delete from flight;
delete from customer;
delete from user_bio_data_otps;
delete from otp;
delete from admin;
delete from user_bio_data;
delete from airport;
